name: usedesk_example
description: Demonstrates how to use the usedesk plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  usedesk:
    path: ../
  shared_preferences: ^2.2.0

  cupertino_icons: ^1.0.5
  file_picker: ^5.3.2
  flutter_chat_ui: ^1.6.9
  image_picker: ^1.0.1
  intl: ^0.18.1
  open_file: ^3.3.2
  uuid: ^3.0.7
  url_launcher: ^6.1.12
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
