name: usedesk
description: Pure dart SDK implementation of usedesk.com service. Includes client realtime chat
repository: https://github.com/ScerIO/usedesk.dart
issue_tracker: https://github.com/ScerIO/usedesk.dart/issues
version: 0.8.0

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  socket_io_client: ^2.0.2
  mime: ^1.0.4
  http: ^1.1.0
  http_parser: ^4.0.2
  filesize: ^2.0.1
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  analyzer: ^5.12.0
